### ISSUE TITLE
problem when I Load json file with 1000 object ?

### ISSUE THREAD

**Issue by khouloudyaakoubi** [sab99r/RecyclerView-LoadMore#2]
Hi , thank you your code is very clear , when i use your code with a json file contains 100  object it work perfectly . But I have a json file contains more than 1000 objects i use volley no data then i use retrofit with list view no data or it take more than 20 minute .I use your code the same problem i cant see my data .
I test your code with a partial json file it work .can you help me to solve the problem ?

**Comment by sab99r** [comment]
Sorry ... the problem relies on your server logic. nothing to do with the android part
